### ISSUE TITLE
去博客园 发文章，提升下知名度。

### ISSUE THREAD

**Issue by sgf** [softlgl/DotNetCoreRpc#11]
去博客园 发文章，提升下知名度。

**Comment by softlgl** [comment]
@sgf 非常感谢提的建议，我打算优化优化再去宣传一下，毕竟写的太烂，容易丢人，还影响大家😸😸

**Comment by sgf** [comment]
> @sgf 非常感谢提的建议，我打算优化优化再去宣传一下，毕竟写的太烂，容易丢人，还影响大家😸😸

序列化这块,可以考虑分离出来,模块化一下,可以考虑引入知名的 序列化框架例如 MessagePack-CSharp 以及作者的新作 MemoryPack

**Comment by softlgl** [comment]
> > @sgf 非常感谢提的建议，我打算优化优化再去宣传一下，毕竟写的太烂，容易丢人，还影响大家😸😸
> 
> 序列化这块,可以考虑分离出来,模块化一下,可以考虑引入知名的 序列化框架例如 MessagePack-CSharp 以及作者的新作 MemoryPack

感谢回复，我正打算看一下`MessagePack`这个呢

**Comment by sgf** [comment]
> > > @sgf 非常感谢提的建议，我打算优化优化再去宣传一下，毕竟写的太烂，容易丢人，还影响大家😸😸
> > 
> > 
> > 序列化这块,可以考虑分离出来,模块化一下,可以考虑引入知名的 序列化框架例如 MessagePack-CSharp 以及作者的新作 MemoryPack
> 
> 感谢回复，我正打算看一下`MessagePack`这个呢
 MessagePack-CSharp 好是好,但是入侵过高, MemoryPack 这个更优秀一些.
